### ISSUE TITLE
Doesn't pass test #4

### ISSUE THREAD

**Issue by ybarlev** [sdsc/sdsc-roll#1]
See error below. The directory "/opt/modulefiles" is not created and populated during the installation.

not ok 4 - /opt/modulefiles in MODULEPATH
# Failed test '/opt/modulefiles in MODULEPATH'
# at /root/rolltests/sdsc.t line 28.
# '/usr/share/Modules/modulefiles:/etc/modulefiles'
# doesn't match '(?-xism:/opt/modulefiles/\w+)'

**Comment by tcooper** [comment]
Thanks for reporting... Resolved in commit [991dba7](https://github.com/sdsc/sdsc-roll/commit/991dba7).
