### ISSUE TITLE
SDSC-Roll Size

### ISSUE THREAD

**Issue by sunracesuraj** [sdsc/sdsc-roll#7]
Hello,

My build ISO of SDSC-roll is around 420 KB in size. Is this correct? 
Also can we simply port these ISO files to any new rock 7 cluster without building these rolls afresh?

![Capture](https://user-images.githubusercontent.com/51955123/60464921-7502d900-9c6d-11e9-943e-27cab18e7923.JPG)

**Comment by tcooper** [comment]
It looks correct.

Trevor Cooper, M.Sc.
HPC Systems Programmer
San Diego Supercomputer Center
________________________________
