### ISSUE TITLE
Failed 2 tests out of 9 is it OK to continue 

### ISSUE THREAD

**Issue by ucerd** [sdsc/sdsc-roll#8]
The test
/root/rolltests/sdsc.t

file gives 2 errors. Are we missing something or its OK for further installations.

ok 1 - sdsc installed
ok 2 - devel files installed
ok 3 - /etc/profile files installed
ok 4 # skip no modulefiles installed
ok 5 # skip /opt/sdsc/lib doesn't exist
ok 6 # skip /opt/sdsc/sbin doesn't exist
ok 7 # skip /opt/sdsc/bin doesn't exist
not ok 8 - SDSCHOME set
Failed test 'SDSCHOME set'
at /root/rolltests/sdsc.t line 46.
got: undef
expected: '/opt/sdsc'

not ok 9 - SDSCDEVEL set
Failed test 'SDSCDEVEL set'
at /root/rolltests/sdsc.t line 47.
got: undef
expected: '/opt/sdsc/devel'

1..9
Looks like you failed 2 tests of 9.

**Comment by tcooper** [comment]
Did you log out and then back in after installation?

The sdsc-roll deploys files into your `/etc/profile.d` directory which are required for normal operation. The easiest way to ensure all changes are applied is to log out and back in before running the roll test.

**Comment by ucerd** [comment]
Thanks 
Now It has passed the tests
